pgsql:
  url: 127.0.0.1
  port: 5432
  user: postgres
  password: 123456
  dbname: blog
mysql:
  url: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  dbname: blog

redis:
  host: 127.0.0.1
  port: 6379
  paswword:
  db: 0
  #  //连接池大小
  poolsize: 100

base:
  name: 梧桐树下
  beian: 浙ICP备2023041529号
  logourl: /images/logo.png
  description: 梧桐树下,是我的个人网站
  keywords: 程序,摄影,go,java,php
#  百度统计 0为不统计
  baidutongji: 0